package com.yayandroid.multipleapplicationcomponent.base

interface ApplicationComponent

interface CoreApplicationComponent: ApplicationComponent

interface FeatureApplicationComponent: ApplicationComponent